name: Market Tracker Bot

on:
  schedule:
    # Bot akan berjalan otomatis setiap hari jam 00:00 UTC (ubah sesuai jam keinginan lo)
    - cron: '0 0 * * *'
  workflow_dispatch: # Memungkinkan lo menjalankan bot secara manual kapan saja dari web GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Run Python Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python bot.py
